### ISSUE TITLE
问下啊，ID是趋势递增的么

### ISSUE THREAD

**Issue by ayamzh** [edwingeng/wuid#12]
问下啊，ID是趋势递增的么？

**Comment by edwingeng** [comment]
是的，默认直接 +1

**Comment by ayamzh** [comment]
收到，那等于应用这边自己混淆下ID就可以了吧。防止推断出用户数量

**Comment by edwingeng** [comment]
如果只担心用户总量的暴露，倒不用混淆，因为这个递增，是一个进程生命期内的递增。重启一下就看不出总量了，还有，服务器之间的数字也不是递增关系
