### ISSUE TITLE
兵哥，tag参数是做什么用的啊

### ISSUE THREAD

**Issue by ayamzh** [edwingeng/wuid#13]
兵哥，tag参数是做什么用的啊

**Comment by edwingeng** [comment]
相当于给 wuid 起个名字，方便在日志中辨别是哪个 wuid 实例

**Comment by ayamzh** [comment]
明白了。是不是就相当于按模块命名，比如用户ID 道具ID 英雄ID生成器




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edwingeng/wuid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午5:34
***@***.***&gt;;
抄送:&nbsp;"阿西巴 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [edwingeng/wuid] 兵哥，tag参数是做什么用的啊 (#13)





 
相当于给 wuid 起个名字，方便在日志中辨别是哪个 wuid 实例

**Comment by ayamzh** [comment]
收到，那比如我有多个模块比如用户，英雄，道具表。都要有一套UUID，这个用什么来区分呢，mysql版的

**Comment by ayamzh** [comment]
是要起多个table么

**Comment by edwingeng** [comment]
> 是要起多个table么

看实际情况，一般不需要，数字足够用。数据库中的数字每加 1，业务进程就能生成接近 2^36 个唯一 ID

**Comment by ayamzh** [comment]
g := wuid.NewWUID("用户IDtag", nil, wuid.WithSection(1))
g := wuid.NewWUID("道具IDtag", nil, wuid.WithSection(2))
这样是不是正确姿势啊 不同业务定义不同的section和tag成对的，表就用一张


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edwingeng/wuid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午5:52
***@***.***&gt;;
抄送:&nbsp;"阿西巴 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [edwingeng/wuid] 兵哥，tag参数是做什么用的啊 (#13)





  
是要起多个table么
  
看实际情况，一般不需要，数字足够用。数据库中的数字每加 1，业务进程就能生成接近 2^36 个唯一 ID

**Comment by edwingeng** [comment]
建议这样：只当某一种业务消耗 ID 特别快，比如一小时 10 亿个，才考虑给它一套独立的 wuid 配置。

至于用户、道具这种程度的区别，用 WithStep 选项生成基础值，再加上一个类型值，比如用户 +1、道具 +5，就够用了。

section 用于在不同的运营大区间做隔离，比如中国区、北美区，平时用不上。

**Comment by ayamzh** [comment]
tags 是不是就对应着mysql里得一条数据啊。  在table之下的

**Comment by edwingeng** [comment]
tag 只用于日志，和 id 生成逻辑没关系，也许应该改个名字，改成 name
